name: 0.build_push-docker-nifi

on:
  workflow_dispatch:

env:
  BASE_IMAGE_TAG: 17-slim-buster
  NIFI_VERSION: 1.17.0
  DISTRO_PATH: 1.17.0
  NIFI_DOCKER_IMAGE_NAME: ldes/nifi
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17

jobs:
  job-build-push-docker-nifi:
    name: Build and push VSDS NiFi docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build NiFi JDK17 Docker image
        run: |
          echo ENVIRONMENT
          echo BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
          echo NIFI_VERSION: ${NIFI_VERSION}
          echo TARGET_IMAGE_TAG: ${NIFI_VERSION}-jdk17
          echo NIFI_DOCKER_IMAGE_NAME: ${NIFI_DOCKER_IMAGE_NAME}
          echo NIFI_DOCKER_IMAGE_VERSION: ${NIFI_DOCKER_IMAGE_VERSION}
          curl -L https://github.com/apache/nifi/archive/refs/tags/rel/nifi-${NIFI_VERSION}.tar.gz | tar -zxv --strip-components=2 nifi-rel-nifi-${NIFI_VERSION}/nifi-docker/dockerhub/
          sed -i 's/xmlstarlet procps$/xmlstarlet procps curl unzip/' dockerhub/Dockerfile
          docker build --build-arg IMAGE_TAG="${BASE_IMAGE_TAG}" --build-arg NIFI_VERSION="${NIFI_VERSION}" --build-arg DISTRO_PATH="${DISTRO_PATH}" -t "${NIFI_DOCKER_IMAGE_NAME}:${NIFI_DOCKER_IMAGE_VERSION}" -f dockerhub/Dockerfile dockerhub/
          docker image push ${NIFI_DOCKER_IMAGE_NAME}:${NIFI_DOCKER_IMAGE_VERSION}
