name: 1.b.pr_build-docker-workbench-nifi

on:
  workflow_run:
    workflows: [1.a.pr_build-maven-packages]
    types: [completed]
  workflow_dispatch:

env:
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17

jobs:
  job-build-docker-workbench-nifi:
    name: Build LDES Workbench NiFi Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build LDES Workbench NiFi Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ldes-workbench-nifi
          push: false
          build-args: |
            NIFI_DOCKER_IMAGE_VERSION=${{ env.NIFI_DOCKER_IMAGE_VERSION }}
