name: 1_b__build-docker-client-cli-image

on:
  workflow_run:
    workflows: [1_a__build-packages]
    types: [completed]
  workflow_dispatch:

jobs:
  job-build-docker-client-cli-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ldes-client
          push: false
