name: 2.a.merge_push-maven-packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job-push-maven-packages:
    name: Build and push LDES Workbench NiFi maven packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Deploy LDES Client Workbench NiFi maven packages to GitHub registry
        env:
          GITHUB_USER_REF: ${{ secrets.USER_NAME }} # Temporary hack to get around PAT for github packages
          GITHUB_TOKEN_REF: ${{ secrets.ACCESS_TOKEN }} # Temporary hack to get around PAT for github packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn deploy
      - name: Copy generated NAR files
        run: |
          cp -pR ${{ github.workspace }}/ldes-client-wrappers-nifi/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsi-ld-to-ldes-processor/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsiv2-to-ngsi-ld-processor/target/*.nar ${{ github.workspace }}
      - name: Upload LDES NiFi nar package
        uses: actions/upload-artifact@v3
        with:
          name: ldes-nar
          path: |
            ${{ github.workspace }}/*.nar
