name: 2.b.merge_push-docker-client-cli

on:
  workflow_run:
    workflows: [2.a.merge_push-maven-packages]
    types: [completed]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: Informatievlaanderen/ldes-client-cli

jobs:
  job-push-docker-client-cli:
    name: Push LDES Client CLI docker image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: Informatievlaanderen
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{env.version}}
            type=raw,value={{date 'YYYYMMDDTHHmm'}}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push LDES Client CLI Docker image to Github registry
        uses: docker/build-push-action@v3
        with:
          context: ./ldes-client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
