name: 2_a__build-and-push-packages-after-merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: Informatievlaanderen/ldes-client-cli

jobs:
  job-build-and-push-packages-after-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn deploy
