name: 4. Publish Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  job-publish-maven-packages:
    name: Publish LDES Client Maven packages to Github registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn deploy
