name: 1.b Build Docker image

on:
  workflow_run:
    workflows: [build-project.yml]
    types: [completed]
  workflow_dispatch:

env:
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17

jobs:
  job-build-docker-workbench-nifi:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Test build LDES Workbench NiFi Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-project.yml
          workflow_conclusion: success
          path: ./ldes-workbench-nifi
          name: ldes-nar
      - name: Build LDES Workbench NiFi Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ldes-workbench-nifi
          push: false
          build-args: |
            NIFI_DOCKER_IMAGE_VERSION=${{ env.NIFI_DOCKER_IMAGE_VERSION }}