name: 2.a Build & Deploy Project (Nar)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: Informatievlaanderen/ldes-cli
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
      - name: Publish Nar to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn deploy
          export VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Copy generated NAR files
        run: |
          cp -pR ${{ github.workspace }}/ldes-client-processor/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsi-ld-to-ldes-processor/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsiv2-to-ngsi-ld-processor/target/*.nar ${{ github.workspace }}
      - name: Upload LDES NiFi nar package
        uses: actions/upload-artifact@v3
        with:
          name: ldes-nar
          path: |
            ${{ github.workspace }}/*.nar