name: 4.a Publish Release (Nar)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18

      - name: Publish Jar to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn deploy
      - name: Copy generated NAR files
        run: |
          cp -pR ${{ github.workspace }}/ldes-client-processor/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsi-ld-to-ldes-processor/target/*.nar ${{ github.workspace }}
          cp -pR ${{ github.workspace }}/ngsiv2-to-ngsi-ld-processor/target/*.nar ${{ github.workspace }}
      - name: Upload LDES NiFi nar package
        uses: actions/upload-artifact@v3
        with:
          name: ldes-nar
          path: |
            ${{ github.workspace }}/*.nar